### ISSUE TITLE
AMALGAMATED=ON does not compile: static name collisions across TUs (parse_pattern, xslt_register_ufn_handlers, set_error, ...)

### ISSUE THREAD

**Issue by ronaldtse** [leptris/leptris#1217]
## Summary

`-DLEPTRIS_AMALGAMATED=ON` fails to compile on current `main` (v1.9.202, commit `4a96591a...` merge state): the generated `leptris_amalgamated.c` compiles every source into one TU, but several `static` functions share names across TUs with **different signatures**, so the single-TU build trips `conflicting types` errors that never appear in the per-file build.

## Repro

```bash
git clone --depth 1 https://github.com/leptris/leptris.git
cmake -S leptris -B leptris/build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DLEPTRIS_AMALGAMATED=ON
cmake --build leptris/build
```

## Errors (first of ~25)

```text
src/leptris/common/format_number.c:124:12: error: conflicting types for 'parse_pattern'
src/leptris/rng/parse.c:92:20: note: previous definition is here
    static RngPattern* parse_pattern(RngGrammar* g, LeptrisElement e, decimal_sep, grouping_sep);

src/leptris/xslt/xslt_functions.c:1577:6: error: conflicting types for 'xslt_register_ufn_handlers'

src/leptris/dtd/validator.c:128:13: error: conflicting types for 'set_error'
```

All three are `static` helpers that collide across TUs (at minimum: `common/format_number.c` vs `rng/parse.c`, `xslt/xslt_functions.c` vs another TU, `dtd/validator.c` vs another TU). In the per-file build the names are file-scoped so nothing conflicts; in the amalgamated TU they merge.

## Why we care

serialbench builds leptris statically on a 13-platform CI matrix. LTO archives (`*_ENABLE_LTO=ON`, the Release default) fail to link under clang's `/usr/bin/ld` (`plugin needed to handle lto object`), so we build with `LEPTRIS_ENABLE_LTO=OFF` — which loses the documented 1.3–3.5× cross-TU inlining wins. The amalgamation build is exactly the documented alternative for that case ("cross-TU inlining without requiring LTO"), but it is currently unbuildable.

## Suggested fix

Rename the colliding `static` functions to be file-unique (or wrap each `#include` in the amalgamation generator with a per-file namespace macro). A CI job that builds `-DLEPTRIS_AMALGAMATED=ON` on at least one platform would keep the mode green.
